In [2]:
import numpy as np # Importa el módulo Numpy
                   # Estructuras de datos multidimensionales (arrays)
                   # Operaciones vectorizadas

#Ejemplos métodos directos de resolución de sistemas de ecuaciones lineales: Factorización LU

##1 Sistemas de ecuaciones lineales

##1.1 Métodos directos

###1.1.1 Método de eliminación gaussiana

Implementación del __método de eliminación gaussiana__:

* __Fase de eliminación__

In [3]:
def eliminacion_gaussiana(A, b):
    """
    * Toma:
    A --> matriz de coeficientes
    b --> matriz de términos independientes
    
    * Devuelve:
    A y b tras aplicar la eliminación
    
    Las matrices se introducen bajo la estructura de numpy.array, de esta manera se optimiza el cálculo
    vectorizando las operaciones.
    
    La rutina pretende ilustrar la implementación en Python del método de eliminación gaussiana.
    """
    
    
    A = A.astype(float) # Los coeficientes de las matrices pasan a expresarse como float
    b = b.astype(float) # Los coeficientes de las matrices pasan a expresarse como float
    
    n = A.shape[0] # n es el número de filas de A (número de ecuaciones)
    
    
    # __ELIMINACIÓN GAUSIANA__    Ax=b --> Ux=c
    # Para las entradas que esten:
    # * En todas las columnas menos la última
    for j in range(0,n-1):
        # * En cada fila con índice superior al de la columna
        for i in range(j+1,n):
            # Si la entrada no es nula
            if A[i,j] != 0.0:
                # Multiplicador, A[j,j] es el pivote, A[i, j] el término
                mult = A[i,j]/A[j,j]
                # A toda la fila de la entrada le restamos la fila superior por el multiplicador
                A[i,:] = A[i,:] - mult*A[j,:]                                     
                b[i] = b[i] - mult*b[j]
    
    # Devuelve
    return A, b 

In [4]:
# Matriz de coeficientes

A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]])
A

array([[ 4, -2,  1],
       [-2,  4, -2],
       [ 1, -2,  4]])

In [5]:
# Matriz de términos independientes

b = np.array([[11],[-16],[17]])
b

array([[ 11],
       [-16],
       [ 17]])

In [6]:
A, b = eliminacion_gaussiana(A, b)

print "A:\n\n", A, "\n\n"
print "b:\n\n", b

A:

[[ 4.  -2.   1. ]
 [ 0.   3.  -1.5]
 [ 0.   0.   3. ]] 


b:

[[ 11. ]
 [-10.5]
 [  9. ]]


* __Sustitución regresiva__

Una vez se ha realizado la fase de eliminación, es necesario aplicar la __sustitución regresiva__ para completar el método.

In [9]:
def sustitucion_regresiva(A, b):
    """
    * Toma:
    A --> matriz de coeficientes escalonada
    b --> matriz de términos independientes escalonada
    
    * Devuelve:
    b --> vector X de las soluciones (Ax=b)
    
    Las matrices se introducen bajo la estructura de numpy.array, de esta manera se optimiza el cálculo
    vectorizando las operaciones.
    
    La rutina pretende ilustrar la implementación en Python del método de sustitución regresiva.
    """
    
    A = A.astype(float) # Los coeficientes de las matrices pasan a expresarse como float
    b = b.astype(float) # Los coeficientes de las matrices pasan a expresarse como float
    
    n = A.shape[0] # n es el número de filas de A (número de ecuaciones)
    
    
    # SUSTUCIÓN REGRESIVA        
    # Desde la última fila hasta la primera
    for j in range(n-1,-1,-1):
        b[j] = (b[j]-np.dot(A[j, j+1:], b[j+1:]))/A[j,j]
        
    return b

In [10]:
# Solución tras aplicar la sustitución regresiva al sistema escalonado

X = sustitucion_regresiva(A, b)

print "X:\n\n", X

X:

[[ 1.]
 [-2.]
 [ 3.]]


Completaremos con el código completo para la resolución de sistemas de ecuaciones lineales mediante la eliminación gaussiana.

In [11]:
def eliminacion_gaussiana_back(A, b):
    """
    * Toma:
    A --> matriz de coeficientes
    b --> matriz de términos independientes
    
    * Devuelve:
    X --> Solución
    
    Las matrices se introducen bajo la estructura de numpy.array, de esta manera se optimiza el cálculo
    vectorizando las operaciones.
    
    La rutina pretende ilustrar la implementación en Python del método de eliminación gaussiana.
    """
    
    A = A.astype(float)
    b = b.astype(float) 
    
    n = A.shape[0] # n es el número de filas de A (ecuaciones)
    
    
    # ELIMINACIÓN GAUSIANA Ax=b --> Ux=c
    # Para las entradas que esten:
    # * En todas las columnas menos la última
    for j in range(0,n-1):
        # * En cada fila con índice superior al de la columna
        for i in range(j+1,n):
            # Si la entrada no es nula
            if A[i,j] != 0.0:
                # Multiplicador, A[j,j] es el pivote, A[i, j] el término
                mult = A[i,j]/A[j,j]
                # A toda la fila de la entrada le restamos la fila superior por el multiplicador
                A[i,:] = A[i,:] - mult*A[j,:]                                     
                b[i] = b[i] - mult*b[j]
               
            
    # SUSTUCIÓN REGRESIVA        
    X = sustitucion_regresiva(A, b)
 
    return X

__Ejemplo__

Podemos resolver un sistema un poco más grande para ver cómo funciona nuestro código.

In [12]:
# Matriz de términos independientes

A = np.array([[5,4,-1,2,-9],[4,3,-5,-5,4],[6,-6,-3,-9,4],[-8,8,5,-3,-6],[-3,-7,2,-5,4]])
A

array([[ 5,  4, -1,  2, -9],
       [ 4,  3, -5, -5,  4],
       [ 6, -6, -3, -9,  4],
       [-8,  8,  5, -3, -6],
       [-3, -7,  2, -5,  4]])

In [13]:
# Matriz de coeficientes

b = np.array([[29],[-65],[-113],[35],[-50]])
b

array([[  29],
       [ -65],
       [-113],
       [  35],
       [ -50]])

In [14]:
# Solución

X = eliminacion_gaussiana_back(A, b)
X

array([[-2.],
       [ 2.],
       [ 3.],
       [ 8.],
       [-2.]])

Podemos terminar comrobando si hemos llegado a la solución correcta.

In [16]:
np.dot(A, X) == b

array([[ True],
       [ True],
       [ True],
       [False],
       [False]], dtype=bool)

Podemos ver que no son exactamente iguales, esto se debe al redondeo en las operaciones de coma flotante.

In [17]:
np.dot(A, X) - b

array([[  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [ -9.37916411e-13],
       [  4.54747351e-13]])

##1.1.3 Sustitución progresiva

In [18]:
def sustitucion_progresiva(A, b):
    """
    * Toma:
    A --> matriz de coeficientes escalonada
    b --> matriz de términos independientes escalonada
    
    * Devuelve:
    x --> vector X de las soluciones (Ax=b)
    
    Las matrices se introducen bajo la estructura de numpy.array, de esta manera se optimiza el cálculo
    vectorizando las operaciones.
    
    La rutina pretende ilustrar la implementación en Python del método de sustitución progresiva.
    """
    
    A = A.astype(float) # Los coeficientes de las matrices pasan a expresarse como float
    b = b.astype(float) # Los coeficientes de las matrices pasan a expresarse como float
    
    n = A.shape[0] # n es el número de filas de A (ecuaciones)
    
    x = np.eye(n,1).astype(float) # Vector para almacenar la solución
    
    # SUSTUCIÓN PROGRESIVA        
    # Desde la última fila hasta la primera
    
    x[0] = b[0]
    for j in range(1,n):
        x[j] = b[j]-np.dot(A[j,0:j], x[0:j])
        
    return x

##2. Factorización $LU$

##2.3 Descomposición de Doolittle

In [19]:
def doolittle(A, b):
    """
    Implementación de la Factorización de Doolittle.
    
    * Toma:
    A --> matriz de coeficientes 
    b --> matriz de términos independientes
    
    * Devuelve:
    L --> triangular inferior de la factorización
    U --> triangular superior de la factorización
    b --> términos independientes (no los modifica)
    x --> solución final LUx=b
    y --> solución parcial Ly=b, Ux=y
    
    Las matrices se introducen bajo la estructura de numpy.array, de esta manera se optimiza el cálculo
    vectorizando las operaciones.
    """
    
    A = A.astype(float)
    b = b.astype(float)
    
    n = A.shape[0] # n es el número de filas de A (ecuaciones)
    
    # El algoritmo para Doolittle es el mismo que en la
    # eliminación gaussiana, solo que almacenamos los multiplicadores
    # en la parte inferior de la diagonal
    
    # Crea una matriz identidad nxn donde almacenaremos los multiplicadores  
    L = np.eye(n,n)
    
    # ELIMINACIÓN GAUSIANA Ax=b --> Ux=c
    # Para las entradas que esten:
    # * En todas las columnas menos la última
    for j in range(0,n-1):
        # * En cada fila con índice superior al de la columna
        for i in range(j+1,n):
            # Si la entrada no es nula
            if A[i,j] != 0.0:
                # Multiplicador, A[j,j] es el pivote, A[i, j] el término
                mult = A[i,j]/A[j,j]
                # A toda la fila de la entrada le restamos la fila superior por el multiplicador
                A[i,:] = A[i,:] - mult*A[j,:]
                # _NO_ modificamos b
                # Almacenamos cada multiplicador en la entrada que elimina pero en L
                L[i,j] = mult

                
    # U es A después de escalonar
    U = A
    
    # Ly=b
    y = sustitucion_progresiva(L, b)
    
    # Ux=y
    x = sustitucion_regresiva(U, y)
    
    return L, U, b, x, y
    

In [20]:
A = np.array([[5,5,0,0,0],[0,5,-7,-2,0],[1,-1,-1,0,0],[0,0,0,2,-3],[0,0,1,-1,1]])
b = np.array([[5.5],[0],[0],[0],[0]])

Ilustremos con un __ejemplo__:

In [21]:
# Matriz de coeficientes
A = np.array([[1,5,2],[-1,0,1],[3,5,4]])
A

array([[ 1,  5,  2],
       [-1,  0,  1],
       [ 3,  5,  4]])

In [22]:
# Matriz de términos independientes
b = np.array([[5],[8],[15]])
b

array([[ 5],
       [ 8],
       [15]])

In [24]:
L, U, b, x, y = doolittle(A, b)

In [25]:
# Matriz identidad con los multiplicadores de la eliminación gaussiana
L

array([[ 1.,  0.,  0.],
       [-1.,  1.,  0.],
       [ 3., -2.,  1.]])

In [26]:
# Matriz A escalonada
U

array([[ 1.,  5.,  2.],
       [ 0.,  5.,  3.],
       [ 0.,  0.,  4.]])

Comprobamos que la factorización es correcta

In [27]:
np.dot(L, U) == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

Entramos en la fase de solución de $Ly=b$ y de $Ux=y$

* Sustitución progresiva en $Ly=b$

In [28]:
y = sustitucion_progresiva(L, b)
y

array([[  5.],
       [ 13.],
       [ 26.]])

* Sustitución regresiva en $Ux=y$

In [31]:
x = sustitucion_regresiva(U, y)
x

array([[-1.5],
       [-1.3],
       [ 6.5]])

El vector x es la solución buscada

In [32]:
# Comprobación 

np.dot(np.dot(L,U), x) == b

array([[ True],
       [ True],
       [ True]], dtype=bool)

##2.4 Descomposición de Choleski

In [33]:
def choleski(A):
    """
    Implementación de la Factorización de Choleski (LL^T=A)
    
    La matriz debe ser:
        * Simétrica
        * Definida positiva (para evitar números complejos)
    
    * Toma:
    A --> matriz de coeficientes 
    
    * Devuelve:
    L --> triangular inferior de la factorización
    
    Las matrices se introducen bajo la estructura de numpy.array, de esta manera se optimiza el cálculo
    vectorizando las operaciones.
    """
    
    A = A.astype(float)
    
    n = A.shape[0] # n es el número de filas de A (ecuaciones)
    
    # Aprovechamos A en el algoritmo en vez de crear L ya que los terminos no se vuelven a emplear
    
    # Para cada columna
    for j in range(n):
        # Si la raiz es un número complejo, lanzamos un error
        try:
            # En los elementos de la diagonal
            A[j,j] = np.sqrt(A[j,j] - np.dot(A[j,0:j],A[j,0:j]))
        except ValueError:
            error.err("La matriz no es definida positiva")
        # En los elementos bajo la diagonal
        for i in range(j+1,n):
            A[i,j] = (A[i,j] - np.dot(A[i,0:j],A[j,0:j]))/A[j,j]
    # En los términos sobre la diagonal
    for j in range(1,n):
        A[0:j,j] = 0.0
   

    return A

In [34]:
# Matriz de coeficientes
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
A

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 3]])

In [35]:
L = choleski(A)
L

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  0.],
       [ 1.,  1.,  1.]])

In [36]:
U = np.transpose(L)
U

array([[ 1.,  1.,  1.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  1.]])

In [68]:
np.dot(L,U) == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

Otro __ejemplo__ de la factorización de Choleski

In [37]:
# Matriz de coeficientes

A = np.array([[1.44,-0.36,5.52,0.00],[-0.36,10.33,-7.78,0.00],[5.52,-7.78,28.40,9.00],[0.00,0.00,9.00,61.00]])
A

array([[  1.44,  -0.36,   5.52,   0.  ],
       [ -0.36,  10.33,  -7.78,   0.  ],
       [  5.52,  -7.78,  28.4 ,   9.  ],
       [  0.  ,   0.  ,   9.  ,  61.  ]])

In [38]:
L = choleski(A)
L

array([[ 1.2,  0. ,  0. ,  0. ],
       [-0.3,  3.2,  0. ,  0. ],
       [ 4.6, -2. ,  1.8,  0. ],
       [ 0. ,  0. ,  5. ,  6. ]])

In [39]:
U = np.transpose(L)
U

array([[ 1.2, -0.3,  4.6,  0. ],
       [ 0. ,  3.2, -2. ,  0. ],
       [ 0. ,  0. ,  1.8,  5. ],
       [ 0. ,  0. ,  0. ,  6. ]])

In [41]:
np.dot(L,U) - A

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   1.77635684e-15,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00]])

##2.5 Matrices dispersas

El siguiente sistema lo almacenamos utilizacdo tres vectores de la forma

$$A =\begin{pmatrix}
1 &4  &0  &0 \\ 
3 &4  &1  &0 \\ 
0 &2  &3  &4 \\ 
0 &0  &1  &3 
\end{pmatrix}, b=\begin{pmatrix}
1\\ 
2\\ 
3\\ 
4
\end{pmatrix}$$

In [43]:
def tridiagonal(c, d, e, b):
    """
    Implementación del algoritmo de Thomas para matrices tridiagonales.
    
    * Toma:
    c --> vector con la subdiagonal 
    d --> vector de la diagonal
    e --> vector de la superdiagonal
    b --> términos independientes
    
    * Devuelve:
    L --> triangular inferior de la factorización
    U --> triangular superior de la factorización
    b --> términos independientes (no los modifica)
    x --> solución final LUx=b
    y --> solución parcial Ly=b, Ux=y
    
    Las matrices se introducen bajo la estructura de numpy.array, de esta manera se optimiza el cálculo
    vectorizando las operaciones.
    """
    
    c = c.astype(float) # Los coeficientes de los vectores pasan a expresarse como float
    d = d.astype(float) # Los coeficientes de los vectores pasan a expresarse como float
    e = e.astype(float) # Los coeficientes de los vectores pasan a expresarse como float
    b = b.astype(float) # Los coeficientes de los vectores pasan a expresarse como float
    
    n = d.shape[0] # n es el número de filas de A (número de ecuaciones)
    
    # FACTORIZACIÓN
    # En esta fase construimos U, que contiene d y e
    # Así como L, compuesta por la identidad más c
    
    # En cada fila desde la segunda
    for i in range(1,n):
        mult = c[i-1]/d[i-1]
        d[i] = d[i] - mult*e[i-1]
        # Almacenamos los multiplicadores en c
        c[i-1] = mult
        
    # RESOLUCIÓN
    # Por comodidad construiremos L y U de manera completa para la resolución
    # Esto no es un gran inconveniente puesto que el grueso de las operaciones
    # ya las hemos realizado usando solo las diagonales
    
    # L 
    
    L = np.eye(n,n)
    
    # Para los elementos de la diagonal inferior (i, j) = (1,0), (2,1), (3,2)...
    for i in range(1, n):
            # Copia el elemento i de c: c[1], c[2]... nunca el 0 del principio
            L[i,i-1] = c[i]
    
    
    # U
    
    U = np.eye(n,n)
    
    for i in range(n-1):
        # Para los elementos de la diagoanl copia d (todos)
        U[i,i] = d[i]
        # Por encima de la diagonal copia todos los de e menos el último (0)
        if (i!=n):
            U[i,i+1] = e[i]
    
    # Ly=b
    
    y = sustitucion_progresiva(L, b)
    
    # Ux=y
    
    x = sustitucion_regresiva(U, y)
    
    
    return L, U, b, x, y

In [44]:
# Diagonal inferior

c = np.array([0,3,2,1])
c

array([0, 3, 2, 1])

In [45]:
# Diagonal

d = np.array([1,4,3,3])
d

array([1, 4, 3, 3])

In [46]:
# Diagonal superior

e = np.array([4,1,4,0])
e

array([4, 1, 4, 0])

In [47]:
# Términos independientes

b = np.array([[1],[2],[3],[4]])
b

array([[1],
       [2],
       [3],
       [4]])

In [48]:
L, U, b, x, y = tridiagonal(c, d, e, b)

In [49]:
# L
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.75      ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.88888889,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  1.        ]])

In [50]:
# U
U

array([[ 1.  ,  4.  ,  0.  ,  0.  ],
       [ 0.  ,  4.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  2.25,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [51]:
# x
x

array([[-3.16358025],
       [ 1.04089506],
       [-2.91358025],
       [ 2.11111111]])

Pordemos comprobar el resultado obtenido

In [53]:
# Comprobación

np.dot(np.dot(L, U), x) - b

array([[  0.00000000e+00],
       [  4.44089210e-16],
       [  0.00000000e+00],
       [  0.00000000e+00]])